
  0%|                                                                                                                                                         | 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/wenhan/Projects/LISA/model/llava_new/LLaVA/llava/train/train.py", line 1161, in <module>
    train()
  File "/home/wenhan/Projects/LISA/model/llava_new/LLaVA/llava/train/train.py", line 1122, in train
    trainer.train()
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/trainer.py", line 2772, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/trainer.py", line 2795, in compute_loss
    outputs = model(**inputs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
TypeError: Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: LlamaForCausalLM.forward() got an unexpected keyword argument 'images'